FROM rackattack-nas.dc1:5000/dev-base-go:2ffac073d15a0ec66d3246df10d91fcf6f09908a

# Install subsystem tests python dependencies
COPY subsystem/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
