FROM rackattack-nas.dc1:5000/staging/python-base-py3:74cc7a7f449b340003ebc92b4c5887a678a60a8a

ADD build/disk-manager-exercise /usr/bin/disk-manager-exercise

COPY lib /tmp/lib

ENTRYPOINT ["disk-manager-exercise"]
