// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Disk Manager Exercise
This is a service to get physical disk information.


    Schemes:
      http
    Host: diskmanagerexercise.service.strato
    BasePath: /api/v2
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
