// Code generated by mockery v1.0.0. DO NOT EDIT.
package restapi

import context "context"
import disk "github.com/Stratoscale/disk-manager-exercise/restapi/operations/disk"
import middleware "github.com/go-openapi/runtime/middleware"
import mock "github.com/stretchr/testify/mock"

// MockDiskAPI is an autogenerated mock type for the DiskAPI type
type MockDiskAPI struct {
	mock.Mock
}

// DiskByID provides a mock function with given fields: ctx, params
func (_m *MockDiskAPI) DiskByID(ctx context.Context, params disk.DiskByIDParams) middleware.Responder {
	ret := _m.Called(ctx, params)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(context.Context, disk.DiskByIDParams) middleware.Responder); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// ListDisks provides a mock function with given fields: ctx, params
func (_m *MockDiskAPI) ListDisks(ctx context.Context, params disk.ListDisksParams) middleware.Responder {
	ret := _m.Called(ctx, params)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(context.Context, disk.ListDisksParams) middleware.Responder); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}
