// Code generated by go-swagger; DO NOT EDIT.

package disk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

/*DiskByIDParams contains all the parameters to send to the API endpoint
for the disk by Id operation typically these are written to a http.Request
*/
type DiskByIDParams struct {

	/*DiskID
	  The ID of the requested disk

	*/
	DiskID string

	Timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *DiskByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.Timeout); err != nil {
		return err
	}
	var res []error

	// path param disk_id
	if err := r.SetPathParam("disk_id", o.DiskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
