// Code generated by go-swagger; DO NOT EDIT.

package disk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the disk client
type API interface {
	// DiskByID retrieves a physical disk
	DiskByID(ctx context.Context, params *DiskByIDParams) (*DiskByIDOK, error)
	// ListDisks lists physical disks
	ListDisks(ctx context.Context, params *ListDisksParams) (*ListDisksOK, error)
}

// New creates a new disk API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for disk API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
DiskByID retrieves a physical disk
*/
func (a *Client) DiskByID(ctx context.Context, params *DiskByIDParams) (*DiskByIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "diskById",
		Method:             "GET",
		PathPattern:        "/disks/{disk_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DiskByIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DiskByIDOK), nil

}

/*
ListDisks lists physical disks
*/
func (a *Client) ListDisks(ctx context.Context, params *ListDisksParams) (*ListDisksOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listDisks",
		Method:             "GET",
		PathPattern:        "/disks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListDisksReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListDisksOK), nil

}
