// Code generated by go-swagger; DO NOT EDIT.

package disk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Stratoscale/disk-manager-exercise/models"
)

// ListDisksReader is a Reader for the ListDisks structure.
type ListDisksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDisksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListDisksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewListDisksBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListDisksOK creates a ListDisksOK with default headers values
func NewListDisksOK() *ListDisksOK {
	return &ListDisksOK{}
}

/*ListDisksOK handles this case with default header values.

successful operation
*/
type ListDisksOK struct {
	Payload models.ListDisksOKBody
}

func (o *ListDisksOK) Error() string {
	return fmt.Sprintf("[GET /disks][%d] listDisksOK  %+v", 200, o.Payload)
}

func (o *ListDisksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDisksBadRequest creates a ListDisksBadRequest with default headers values
func NewListDisksBadRequest() *ListDisksBadRequest {
	return &ListDisksBadRequest{}
}

/*ListDisksBadRequest handles this case with default header values.

Invalid filter
*/
type ListDisksBadRequest struct {
}

func (o *ListDisksBadRequest) Error() string {
	return fmt.Sprintf("[GET /disks][%d] listDisksBadRequest ", 400)
}

func (o *ListDisksBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
