// Code generated by go-swagger; DO NOT EDIT.

package disk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

/*ListDisksParams contains all the parameters to send to the API endpoint
for the list disks operation typically these are written to a http.Request
*/
type ListDisksParams struct {

	/*Hostname
	  The hostname of the specified node

	*/
	Hostname *string

	Timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *ListDisksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.Timeout); err != nil {
		return err
	}
	var res []error

	if o.Hostname != nil {

		// query param hostname
		var qrHostname string
		if o.Hostname != nil {
			qrHostname = *o.Hostname
		}
		qHostname := qrHostname
		if qHostname != "" {
			if err := r.SetQueryParam("hostname", qHostname); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
