// Code generated by go-swagger; DO NOT EDIT.

package diskmanagerexerciseclient

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"net/url"

	"github.com/go-openapi/runtime"
	rtclient "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Stratoscale/disk-manager-exercise/diskmanagerexerciseclient/disk"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "diskmanagerexercise.service.strato"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v2"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

type Config struct {
	// URL is the base URL of the upstream server
	URL *url.URL
	// Transport is an inner transport for the client
	Transport http.RoundTripper
	// AuthInfo is for authentication
	AuthInfo runtime.ClientAuthInfoWriter
}

// New creates a new disk manager exercise HTTP client.
func New(c Config) *DiskManagerExercise {
	var (
		host     = DefaultHost
		basePath = DefaultBasePath
		schemes  = DefaultSchemes
	)

	if c.URL != nil {
		host = c.URL.Host
		basePath = c.URL.Path
		schemes = []string{c.URL.Scheme}
	}

	transport := rtclient.New(host, basePath, schemes)
	if c.Transport != nil {
		transport.Transport = c.Transport
	}

	cli := new(DiskManagerExercise)
	cli.Transport = transport
	cli.Disk = disk.New(transport, strfmt.Default, c.AuthInfo)
	return cli
}

// DiskManagerExercise is a client for disk manager exercise
type DiskManagerExercise struct {
	Disk      *disk.Client
	Transport runtime.ClientTransport
}
