// Code generated by go-swagger; DO NOT EDIT.

package disk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DiskByIDHandlerFunc turns a function with the right signature into a disk by Id handler
type DiskByIDHandlerFunc func(DiskByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DiskByIDHandlerFunc) Handle(params DiskByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DiskByIDHandler interface for that can handle valid disk by Id params
type DiskByIDHandler interface {
	Handle(DiskByIDParams, interface{}) middleware.Responder
}

// NewDiskByID creates a new http.Handler for the disk by Id operation
func NewDiskByID(ctx *middleware.Context, handler DiskByIDHandler) *DiskByID {
	return &DiskByID{Context: ctx, Handler: handler}
}

/*DiskByID swagger:route GET /disks/{disk_id} disk diskById

Retrieve a physical disk

*/
type DiskByID struct {
	Context *middleware.Context
	Handler DiskByIDHandler
}

func (o *DiskByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDiskByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
