// Code generated by go-swagger; DO NOT EDIT.

package disk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListDisksHandlerFunc turns a function with the right signature into a list disks handler
type ListDisksHandlerFunc func(ListDisksParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListDisksHandlerFunc) Handle(params ListDisksParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListDisksHandler interface for that can handle valid list disks params
type ListDisksHandler interface {
	Handle(ListDisksParams, interface{}) middleware.Responder
}

// NewListDisks creates a new http.Handler for the list disks operation
func NewListDisks(ctx *middleware.Context, handler ListDisksHandler) *ListDisks {
	return &ListDisks{Context: ctx, Handler: handler}
}

/*ListDisks swagger:route GET /disks disk listDisks

List physical disks

*/
type ListDisks struct {
	Context *middleware.Context
	Handler ListDisksHandler
}

func (o *ListDisks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListDisksParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
