// Code generated by go-swagger; DO NOT EDIT.

package disk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListDisksParams creates a new ListDisksParams object
// no default values defined in spec.
func NewListDisksParams() ListDisksParams {

	return ListDisksParams{}
}

// ListDisksParams contains all the bound params for the list disks operation
// typically these are obtained from a http.Request
//
// swagger:parameters listDisks
type ListDisksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The hostname of the specified node
	  In: query
	*/
	Hostname *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListDisksParams() beforehand.
func (o *ListDisksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qHostname, qhkHostname, _ := qs.GetOK("hostname")
	if err := o.bindHostname(qHostname, qhkHostname, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListDisksParams) bindHostname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Hostname = &raw

	return nil
}
