// Code generated by go-swagger; DO NOT EDIT.

package disk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Stratoscale/disk-manager-exercise/models"
)

// ListDisksOKCode is the HTTP code returned for type ListDisksOK
const ListDisksOKCode int = 200

/*ListDisksOK successful operation

swagger:response listDisksOK
*/
type ListDisksOK struct {

	/*
	  In: Body
	*/
	Payload models.ListDisksOKBody `json:"body,omitempty"`
}

// NewListDisksOK creates ListDisksOK with default headers values
func NewListDisksOK() *ListDisksOK {
	return &ListDisksOK{}
}

// WithPayload adds the payload to the list disks o k response
func (o *ListDisksOK) WithPayload(payload models.ListDisksOKBody) *ListDisksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list disks o k response
func (o *ListDisksOK) SetPayload(payload models.ListDisksOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListDisksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.ListDisksOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ListDisksBadRequestCode is the HTTP code returned for type ListDisksBadRequest
const ListDisksBadRequestCode int = 400

/*ListDisksBadRequest Invalid filter

swagger:response listDisksBadRequest
*/
type ListDisksBadRequest struct {
}

// NewListDisksBadRequest creates ListDisksBadRequest with default headers values
func NewListDisksBadRequest() *ListDisksBadRequest {
	return &ListDisksBadRequest{}
}

// WriteResponse to the client
func (o *ListDisksBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
